# Generated by Django 4.0.4 on 2022-05-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200, null=True)),
                ('theme', models.CharField(max_length=200, null=True)),
                ('people', models.IntegerField(null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('package', models.CharField(choices=[('Basic Deposit', 'Base'), ('Premium Deposit', 'Premium'), ('Gold Deposit', 'Gold')], max_length=200, null=True)),
                ('select_date', models.DateField()),
                ('client', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('type', models.CharField(max_length=200, null=True)),
                ('theme', models.CharField(max_length=200, null=True)),
                ('people', models.IntegerField(null=True)),
                ('request_date', models.DateField()),
                ('address', models.CharField(max_length=200, null=True)),
                ('package', models.CharField(choices=[('Basic Deposit', 'Base'), ('Premium Deposit', 'Premium'), ('Gold Deposit', 'Gold')], max_length=200, null=True)),
                ('terms_and_conditions', models.BooleanField(null=True)),
            ],
        ),
    ]
