# Generated by Django 3.2.7 on 2022-04-18 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220418_2044'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='attendees',
            new_name='people',
        ),
    ]
