# Generated by Django 3.2.7 on 2022-04-19 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220419_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='people',
        ),
    ]
