# Generated by Django 3.2.7 on 2022-04-19 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_event_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='approved',
        ),
    ]
