# Generated by Django 3.2.7 on 2022-04-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_event_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('type', models.CharField(max_length=200, null=True)),
                ('theme', models.CharField(max_length=200, null=True)),
                ('people', models.IntegerField(null=True)),
                ('request_date', models.DateField()),
                ('address', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
