# Generated by Django 3.2.7 on 2022-04-22 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_event_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='select_date',
            field=models.DateTimeField(),
        ),
    ]
