# Generated by Django 4.0.4 on 2022-05-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_requestevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestevent',
            name='package',
            field=models.CharField(choices=[('Base', 'Base'), ('Premium', 'Premium'), ('Gold', 'Gold')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='requestevent',
            name='terms_and_conditions',
            field=models.BooleanField(null=True),
        ),
    ]
