# Generated by Django 4.0.4 on 2022-05-05 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_requestevent_package_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestevent',
            name='package',
        ),
    ]
