# Generated by Django 3.2.7 on 2022-05-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_requestevent_package_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestevent',
            name='package',
            field=models.CharField(choices=[('Basic Deposit', 'Base'), ('Premium Deposit', 'Premium'), ('Gold Deposit', 'Gold')], max_length=200, null=True),
        ),
    ]
