# Generated by Django 3.2.7 on 2022-05-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_requestevent_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestevent',
            name='package',
            field=models.CharField(choices=[('Basic Deposit', 'Base'), ('Premium Deposit', 'Premium'), ('Gold Deposit', 'Gold')], max_length=200),
        ),
    ]
