# Generated by Django 3.2.7 on 2022-05-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_requestevent_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestevent',
            name='package',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
