# Generated by Django 3.2.7 on 2022-05-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_requestevent_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='package',
            field=models.CharField(choices=[('Basic Deposit', 'Base'), ('Premium Deposit', 'Premium'), ('Gold Deposit', 'Gold')], max_length=200, null=True),
        ),
    ]
